### ISSUE TITLE
400 bad request when using dynamic complex keys

### ISSUE THREAD

**Issue by gauravbh1** [cloudant/java-cloudant#402] opened 2017-12-09 16:51 UTC
I am dynamically generating complex keys and passing it to the keys in the API (as shown in the code snippet below).

The issue is that I start getting the following 400 bad request error once the dynamic complex keys start growing.
com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request at 
	at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:528)
	at com.cloudant.client.api.CloudantClient.executeRequest(CloudantClient.java:339)
	at com.cloudant.client.internal.views.ViewRequester.executeRequestWithResponseAsJson(ViewRequester.java:34)
	at com.cloudant.client.internal.views.ViewRequester.getResponseAsJson(ViewRequester.java:28)
	at com.cloudant.client.internal.views.ViewRequestImpl.getResponse(ViewRequestImpl.java:34)

I have provided the code to simulate the issue. In the code if I change the values of variable **tries** to let's say 300 then there is no issue. But at 450, I start getting the above-mentioned error.

Is there something wrong that I am doing while using the API or is it really a bug? 

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
   2.10.0
- Java version (including vendor and platform).
   java version "1.8.0_141"
  Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
  Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

- If you're using the optional okhttp dependency.
- A small code sample that demonstrates the issue.

        List<ComplexKey> keys = new ArrayList<>();
	    int tries = 450;
	    for(int i = 0 ; i < tries ; i++) {
	    	ComplexKey key  = Key.complex("abc"+i);
	    	key.add(1);
	    	keys.add(key);   	
	    }
	    ComplexKey[] array = {};
	    array = keys.toArray(array);

		ViewResponse<ComplexKey, String> response = null;
		Database db = client.database("mydb", false);
		if(db != null) {
			ViewRequestBuilder viewBuilder = db.getViewRequestBuilder("mydesigndocs", "myview");
			if(viewBuilder != null) {
				ViewRequest<ComplexKey, String> request = viewBuilder.newRequest(Key.Type.COMPLEX,String.class)
						.keys(array)
						.includeDocs(false)
						.build();

				try {
					if(request != null) {						
						response = request.getResponse();
					}
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}

**Comment by gauravbh1** [comment] 2017-12-09 16:52
Couch db version is 2.1.0

**Comment by ricellis** [comment] 2017-12-11 09:36
The view request in java-cloudant is done by a `GET`, using too many keys causes it to exceed the URL length limit. See #196.
I have occasionally seen the correct `414` status code, but mostly it seems to return a `400` (possibly from trying to parse truncated JSON).

This limitation does not apply to a `POST`. [See this comment](https://github.com/cloudant/java-cloudant/issues/196#issuecomment-316027548) for a workaround to use a `POST` instead of a `GET`, which works with CouchDB 2+ and Cloudant accounts.

**Comment by tomblench** [comment] 2018-01-09 10:02
closing, duplicate of #196

**Closed by tomblench** 2018-01-09 10:02 UTC
Labels: duplicate
