### ISSUE TITLE
Database bulk method incorrectly deserialising object

### ISSUE THREAD

**Issue by stephen-kruger** [cloudant/java-cloudant#160] opened 2015-11-29 21:26 UTC
I have a POJO with a few public String fields.
When passing a list of them to the database.bulk(); method, when they have some non-standard char encodings (chinese for e.g.) the operation fails with :
`com.cloudant.client.org.lightcouch.CouchDbException: Error retrieving server response
	at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:501)
	at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:515)
	at com.cloudant.client.org.lightcouch.CouchDbClient.post(CouchDbClient.java:422)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.bulk(CouchDatabaseBase.java:276)
	at com.cloudant.client.api.Database.bulk(Database.java:886)
	at ...`

Here is the method used to set the string values causing the failure :
```javascript
public static String randomChinese(int length){
		final int chineseStart = Integer.parseInt(String.valueOf(0x4e00));
		final int chineseEnd = Integer.parseInt(String.valueOf(0x9FA5));
		StringBuffer sb = new StringBuffer();
		for (int i = 0; i < length; i++) {
			int position = random.nextInt(chineseEnd-chineseStart)+chineseStart;
			String code = Integer.toHexString(position);
			sb.append(decode("\\u"+code));
		}
		return sb.toString();	
}
```

**Comment by stephen-kruger** [comment] 2015-11-30 00:25
Sorry, here is the nested exception 
```
Caused by: java.io.IOException: too many bytes written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3452)
	at com.cloudant.http.HttpConnection.execute(HttpConnection.java:234)
	at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:466)
	... 48 more
```

I managed to fix the error by running this code to set the strings, afer which the db.bulk() calls works normally.

```javascript
Charset.forName("UTF-8").encode(sb.toString()).toString()
```

**Comment by ricellis** [comment] 2015-11-30 07:40
I think this is a duplicate of #155 which is already fixed in the master branch.

**Closed by ricellis** 2015-11-30 07:40 UTC
Labels: duplicate
