### ISSUE TITLE
OkHttp library default Idle connection timeout

### ISSUE THREAD

**Issue by sagardiwan** [cloudant/java-cloudant#366] opened 2017-08-17 20:50 UTC
Hi,

What is the default idle connection timeout value when using OkHttp library ? Is this configurable ?

Note:  I had opened a thread earlier , and then cloudant had a server side timeout of 2.5 minutes, but based on our recent communication with cloudant support , we found that they have higher limits now , upto 1 hr but subject to change.

Thanks.

**Comment by smithsz** [comment] 2017-08-18 11:06
Hi @sagardiwan, we set a client timeout of 2.5 minutes on our load balancers. The 60 minute timeout that Cloudant Support were referring to must have been the server timeout. This is for requests between the load balancer and backend database nodes.

The idle timeout when using OkHttp is set to 3 minutes [here](https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java#L105). Bear in mind that this is not currently configurable. This was chosen in order to keep the connections open for as long as possible (noting that they will be terminated by the server at 2.5 minutes).

We'll do some further investigating our side to ensure the client isn't failing to detect closed connections (or similar) and will be in touch shortly with our findings.

**Comment by sagardiwan** [comment] 2017-08-18 13:11
Thanks @smithsz  

We are using netscaler LB , and have set client timeout = 3 mins and server side timeout = 6mins

With those settings , our applications sees frequent connections resets , almost  8-10 times an hour.

**Comment by ricellis** [comment] 2017-08-25 09:18
I’ve run through some test scenarios and with respect to connection lifetimes in the pool the OkHttp library appears to detect connections closed by the Cloudant LBs without any problem, successfully re-opening new connections when required. See also [my comment on another ConnectionReset issue](https://github.com/cloudant/java-cloudant/issues/356#issuecomment-310021871). I don’t know about how NetScaler handles connections or keep-alive, but you may want to try and identify where the TCP `RST` is coming from as that may make it clear what is happening. It appears that if you can capture the packet there are some [codes available](https://www.citrix.com/blogs/2014/05/20/whats-that-netscaler-reset-packet/).

Given that it’s possible this isn’t caused by pooling at all I think identifying the `RST` is your best course of action. Failing that an alternative may be to allow the client to take control of closing the connections to NetScaler. As discussed the client will close idle connections after 3 minutes so if you set your NetScaler client side keep-alive to > 3 min then the client might be able to purge them first. You may also want to set your NetScaler server side timeout to < 2.5 min so that it can close the connection with Cloudant before Cloudant does.

How many connections are you trying to maintain between client and NetScaler (i.e. `ClientBuilder#maxConnections()`) and how many `CloudantClient` instances do you have? How many connections are you maintaining between NetScaler and your Cloudant account(s)?

**Comment by ricellis** [comment] 2017-09-21 13:34
Closing as stale, please re-open if you provide answers to the above questions.

**Closed by ricellis** 2017-09-21 13:34 UTC
Labels: question
