### ISSUE TITLE
Receiving .IllegalStateException when attempting to "get" a Design Document using the DesignDocumentManager class.

### ISSUE THREAD

**Issue by pankeyg** [cloudant/java-cloudant#259] opened 2016-05-13 16:53 UTC
Code snippet:			
			Database db = client.database(dbName, false);
			
			DesignDocumentManager ddMgr = db.getDesignDocumentManager();
			DesignDocument dd = ddMgr.get(designDoc);

Attempting to retrieve this design doc:
{
    "_id": "_design/support-index",
    "_rev": "2-d59ad88656e965aa2d560e38d1c5892f",
    "language": "query",
    "views": {
        "support-index": {
            "map": {
                "fields": {
                    "TransactionDocumentBody.Transaction.TransactionEffectiveDate": "asc"
                }
            },
            "reduce": "_count",
            "options": {
                "def": {
                    "fields": [
                        "TransactionDocumentBody.Transaction.TransactionEffectiveDate"
                    ]
                },
                "w": 2
            }
        }
    }
}

Cloudant version:
Server Version: 0.1.0-local

Error stack:
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 128
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at com.cloudant.client.org.lightcouch.internal.CouchDbUtil.getResponse(CouchDbUtil.java:216)
	at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:329)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(CouchDatabaseBase.java:88)
	at com.cloudant.client.api.Database.find(Database.java:540)
	at com.cloudant.client.api.DesignDocumentManager.get(DesignDocumentManager.java:147)

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
Version 2.4.3
- Java version (including vendor and platform).
Version 1.8
- If you're using the optional okhttp dependency.
Am not using okhttp
- A small code sample that demonstrates the issue.

**Comment by ricellis** [comment] 2016-05-16 07:35
Thanks for reporting this, it is a known problem deserializing `DesignDocument` that contain query indexes. Closing as a duplicate of #239.

**Closed by ricellis** 2016-05-16 07:35 UTC
Labels: duplicate
