### ISSUE TITLE
Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull

### ISSUE THREAD

**Issue by yourlearning** [cloudant/java-cloudant#354] opened 2017-05-15 07:26 UTC
Version 2.8.0
Server Version: 1.0.2
Gson: 2.7

When calling:

`db.getAllDocsRequestBuilder().keys(docIds).includeDocs(true).build().getResponse().getDocsAs(JsonObject.class));`

and docIds contains 

`String docIds[] = { "CNL_LCB_1462291097069", "CNL_REC_BUSGRP-JOBCAT-CHQ-HR" };`

one of the ids doesn't exist, I got:

```
Exception in thread "main" com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.Gson.fromJson(Gson.java:925)
	at com.cloudant.client.internal.views.RowImpl.getDocumentAsType(RowImpl.java:65)
	at com.cloudant.client.internal.views.ViewResponseImpl.getDocsAs(ViewResponseImpl.java:180)
	at com.cloudant.client.internal.views.AllDocsRequestResponse.getDocsAs(AllDocsRequestResponse.java:67)
	at com.ibm.lex.services.channels.database.Cloudant.main(Cloudant.java:632)
```

1. One non-existing id:

`String docIds[] = { "CNL_REC_BUSGRP-JOBCAT-CHQ-HR" };`

returns empty result `[]` - OK

2. One existing id:

`String docIds[] = { "CNL_LCB_1462291097069" };`

returns object `[{"_id":"CNL_LCB_1462291097069","_rev":"604-c06cd3de1712...` - OK

3. One existing and non-existing id:

`String docIds[] = { "CNL_LCB_1462291097069", "CNL_REC_BUSGRP-JOBCAT-CHQ-HR" };`

returns `com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull`

**Comment by ricellis** [comment] 2017-05-15 08:17
@smithsz can you take a look at this? I think it is slightly similar to issue #297, but in this case the `com.cloudant.client.internal.views.RowImpl` needs the `getDocument()` and `getDocumentAsType(Class<D>)` methods to be corrected to handle cases where the `row.get("doc")` returns `null` since the document doesn't exist.

**Comment by smithsz** [comment] 2017-05-16 13:24
@yourlearning Hi, I'm afraid I haven't been able to reproduce this issue. The following returns a list with a null element as expected.
```java
db.getAllDocsRequestBuilder().keys(new String[{"missing_id"})
    .includeDocs(true).build().getResponse().getDocsAs(JsonObject.class);
```
Are you customising gson at all?

**Comment by emlaver** [comment] 2017-11-13 19:16
We've improved the handling of non-existent doc IDs in view response in #380 .  Closing this ticket.

**Closed by emlaver** 2017-11-13 19:16 UTC
Labels: bug
